server.port=8081

spring.data.redis.host=${REDIS_HOST}
pring.data.redis.port=${REDIS_PORT:6379}

aws.region=${AWS_REGION}
aws.dynamodb.table=${DYNAMODB_TABLE}

aws.dynamodb.endpoint=${DYNAMODB_ENDPOINT:}
