server:
  port: 8081

aws:
  region: ${AWS_REGION}
  dynamodb:
    warehouses-table: ${WAREHOUSE_TABLE_NAME}
    outbox-table: ${OUTBOX_TABLE_NAME}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${COGNITO_ISSUER_URI}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
