server:
  port: 8083

aws:
  region: ${AWS_REGION}
  dynamodb:
    shipments-table: ${SHIPMENT_TABLE_NAME}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${COGNITO_ISSUER_URI}
