server:
  port: 8083

aws:
  region: ${AWS_REGION}
  dynamodb:
    shipments-table: ${SHIPMENT_TABLE_NAME}
    outbox-table: ${SHIPPING_OUTBOX_TABLE_NAME}
    warehouse-access-table: ${WAREHOUSE_ACCESS_TABLE_NAME}
  s3:
    shipping-guides-bucket: fulfillment-shipping-guides

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${COGNITO_ISSUER_URI}

springdoc:
  api-docs:
    version: OPENAPI_3_0
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
