server:
  port: 8083

aws:
  region: us-east-1
  dynamodb:
    endpoint: "http://localhost:8000"
    shipments-table: Shipments
    outbox-table: ShippingOutbox
  s3:
    endpoint: "http://localhost:4566"
    shipping-guides-bucket: local-shipping-guides

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
