server:
  port: 8080

aws:
  region: us-east-1
  dynamodb:
    endpoint: "http://localhost:8000"
    orders-table: Orders
    history-table: OrdersStateHistory
    outbox-table: OutboxEvents

springdoc:
  api-docs:
    version: OPENAPI_3_0
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
