warehouse.service.base-url=${WAREHOUSE_BASE_URL}
server.port=8080

aws.region=${AWS_REGION}
aws.dynamodb.orders-table=${ORDER_TABLE_NAME}
aws.dynamodb.history-table=${ORDER_HISTORY_TABLE_NAME}

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT:6379}
