server:
  port: 8080

aws:
  region: ${AWS_REGION}
  dynamodb:
    orders-table: ${ORDER_TABLE_NAME}
    history-table: ${ORDER_HISTORY_TABLE_NAME}
    outbox-table: ${OUTBOX_TABLE_NAME}

spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${COGNITO_ISSUER_URI}
springdoc:
  api-docs:
    version: OPENAPI_3_0
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha