server.port=8080

aws.region=us-east-1
aws.dynamodb.endpoint=http://localhost:8000
aws.dynamodb.orders-table=Orders
aws.dynamodb.history-table=OrdersStateHistory
aws.dynamodb.outbox-table=OutboxEvents
