server.port=8090

worker.maxConcurrentProcessing=5

aws.region=us-east-1

aws.sqs.queueUrl=http://localhost:4566/098765/OrderEventsQueue
aws.sqs.waitTimeSeconds=10
aws.sqs.maxMessages=10
aws.sqs.visibilityTimeoutSeconds=30

aws.dynamodb.endpoint=http://localhost:8000
aws.dynamodb.ordersTable=Orders
aws.dynamodb.historyTable=OrdersStateHistory

services.warehouse.baseUrl=http://localhost:8081
services.inventory.baseUrl=http://localhost:8082
