server.port=8090

worker.poll.fixedDelayMs=${WORKER_POLL_DELAY_MS:1000}

aws.region=${AWS_REGION}

aws.sqs.queueUrl=${SQS_QUEUE_URL}
aws.sqs.waitTimeSeconds=${SQS_WAIT_TIME_SECONDS:10}
aws.sqs.maxMessages=${SQS_MAX_MESSAGES:10}
aws.sqs.visibilityTimeoutSeconds=${SQS_VISIBILITY_TIMEOUT_SECONDS:30}

aws.dynamodb.ordersTable=${ORDER_TABLE_NAME}
aws.dynamodb.historyTable=${ORDER_HISTORY_TABLE_NAME}

services.warehouse.baseUrl=${WAREHOUSE_BASE_URL}
services.inventory.baseUrl=${INVENTORY_BASE_URL}
